# Generated by Django 5.0.1 on 2024-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBikefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavalo', models.FloatField()),
                ('esterno', models.FloatField()),
                ('braco', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
