# Generated by Django 5.0.1 on 2024-01-05 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbikefit',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
