# Generated by Django 5.0.1 on 2024-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0002_modelbikefit_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBikefitLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('link', models.URLField()),
            ],
        ),
    ]
