# Generated by Django 5.0.1 on 2024-01-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0003_modelbikefitlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelbikefit',
            options={'verbose_name': 'Cálculos de bikefit'},
        ),
    ]
