# Generated by Django 5.0.1 on 2024-01-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0004_alter_modelbikefit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelbikefit',
            options={'verbose_name': 'Cálculos de bikefit', 'verbose_name_plural': 'Cálculos de bikefit'},
        ),
        migrations.AlterModelOptions(
            name='modelbikefitlinks',
            options={'verbose_name': 'Lista de Links', 'verbose_name_plural': 'Lista de Links'},
        ),
    ]
