# Generated by Django 5.0.1 on 2024-01-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_banco', models.IntegerField(max_length=10)),
                ('proxima_parcela', models.CharField(max_length=10)),
                ('ultima_parcela', models.CharField(max_length=10)),
                ('quantidade_parcelas', models.IntegerField(max_length=5)),
                ('valor_parcela', models.CharField(max_length=20)),
                ('valor_emprestado', models.CharField(max_length=20)),
            ],
        ),
    ]
