# Generated by Django 4.2.1 on 2024-03-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_banco', models.CharField(max_length=10)),
                ('proxima_parcela', models.CharField(max_length=10)),
                ('ultima_parcela', models.CharField(max_length=10)),
                ('quantidade_parcelas', models.CharField(max_length=10)),
                ('valor_parcela', models.CharField(max_length=20)),
                ('valor_emprestado', models.CharField(max_length=20)),
                ('data_calculo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dados para calcular PCD',
                'verbose_name_plural': 'Dados para calcular PCD',
            },
        ),
    ]
