# Generated by Django 5.0.1 on 2024-01-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpcd',
            name='codigo_banco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelpcd',
            name='quantidade_parcelas',
            field=models.IntegerField(),
        ),
    ]
