# Generated by Django 5.0.1 on 2024-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0003_modelpcd_data_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpcd',
            name='csrfmiddlewaretoken',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
