# Generated by Django 5.0.1 on 2024-01-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0004_modelpcd_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpcd',
            name='csrfmiddlewaretoken',
        ),
    ]
