# Generated by Django 5.0.1 on 2024-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0005_remove_modelpcd_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpcd',
            name='codigo_banco',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelpcd',
            name='quantidade_parcelas',
            field=models.CharField(max_length=10),
        ),
    ]
