# Generated by Django 5.0.1 on 2024-01-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0006_alter_modelpcd_codigo_banco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpcd',
            options={'verbose_name': 'Dados para calcular PCD', 'verbose_name_plural': 'Dados para calcular PCD'},
        ),
    ]
