# Generated by Django 4.2.1 on 2024-03-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=200)),
                ('variedade', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=100)),
                ('secagem', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localidade', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TorraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_inicial', models.CharField(max_length=10)),
                ('temperatura_final', models.CharField(max_length=10)),
                ('temperatura_piso', models.CharField(max_length=10)),
                ('fluxo_ar', models.CharField(max_length=10)),
                ('velocidade_tambor', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('data_torra', models.DateField()),
                ('dados_torra', models.JSONField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafemodel')),
            ],
        ),
        migrations.AddField(
            model_name='cafemodel',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.produtormodel'),
        ),
    ]
