# Generated by Django 5.0.1 on 2024-02-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=200)),
                ('variedade', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=100)),
                ('secagem', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=50)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.produtormodel')),
            ],
        ),
    ]
