# Generated by Django 5.0.1 on 2024-02-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_inicial', models.CharField(max_length=10)),
                ('temperatura_final', models.CharField(max_length=10)),
                ('tempratura_piso', models.CharField(max_length=10)),
                ('fluxo_ar', models.CharField(max_length=10)),
                ('velocidade_tambor', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('data_torra', models.DateField()),
                ('dados_torra', models.JSONField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafemodel')),
            ],
        ),
    ]
