# Generated by Django 5.0.1 on 2024-02-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_torramodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='torramodel',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
